#!/usr/bin/env swift
// generate_upcase_table.swift
//
// Auditable generator for the canonical NTFS $UpCase table — emits
// Packages/NTFSCore/Sources/NTFSCore/UpcaseTable.swift.
//
// Source of truth:
//   Per-codepoint Unicode default case-folding (simple, single-codepoint
//   uppercase mapping). This is the same data that powers Swift's
//   String.uppercased() on a single-scalar string for BMP codepoints.
//   The NTFS $UpCase table is a 65,536-entry UTF-16-codepoint → uppercase
//   UTF-16-codepoint map (128 KiB total, little-endian).
//
// IMPORTANT (clean-room): we DO NOT copy any bytes or code from
// `ntfsprogs`/`mkntfs-3g/libntfs/upcase.c` (which is GPL). We instead
// derive the mappings from the Unicode case database, accessed through
// the Swift standard library's case-mapping APIs (which are themselves
// derived from Unicode's UnicodeData.txt + SpecialCasing.txt).
//
// Rules (matching how mkntfs-3g and Windows treat BMP codepoints):
//   1. For each codepoint c in [0x0000, 0xFFFF]:
//        upper = simple uppercase mapping of c.
//   2. If the simple uppercase mapping expands to more than one codepoint
//      (e.g. German ß → SS), the NTFS table maps c to itself (no fold).
//   3. Surrogate halves [0xD800, 0xDFFF] map to themselves.
//
// Run with: swift scripts/generate_upcase_table.swift > /tmp/Upcase.swift
// (or pass an explicit output path as the first argument).

import Foundation

func simpleUppercase(_ cp: UInt32) -> UInt32 {
    // Surrogate halves: no-op.
    if (0xD800...0xDFFF).contains(cp) { return cp }
    // Build a single-scalar string and uppercase it. We rely on Swift's
    // built-in case mapping (Unicode-derived).
    guard let scalar = Unicode.Scalar(cp) else { return cp }
    let s = String(Character(scalar))
    let u = s.uppercased()
    let scalars = Array(u.unicodeScalars)
    // Rule 2: skip multi-codepoint expansions (e.g. ß → SS, ﬃ → FFI).
    guard scalars.count == 1 else { return cp }
    let mapped = scalars[0].value
    // Stay within BMP — the $UpCase table is 16-bit.
    guard mapped <= 0xFFFF else { return cp }
    return mapped
}

let outPath: String
if CommandLine.arguments.count >= 2 {
    outPath = CommandLine.arguments[1]
} else {
    outPath = "Packages/NTFSCore/Sources/NTFSCore/UpcaseTable.swift"
}

var bytes: [UInt8] = []
bytes.reserveCapacity(131_072)
for cp in 0..<UInt32(65_536) {
    let u = simpleUppercase(cp)
    bytes.append(UInt8(u & 0xFF))
    bytes.append(UInt8((u >> 8) & 0xFF))
}
precondition(bytes.count == 131_072, "upcase table must be 128 KiB exactly")

// Emit as a Swift source file with a single `static let bytes: [UInt8]` —
// we wrap into Data at call-sites. A flat array literal is the simplest
// form Swift's parser handles; we wrap 16 bytes/line for readability.
var out = ""
out += """
// AUTO-GENERATED by scripts/generate_upcase_table.swift. DO NOT EDIT.
//
// NTFS $UpCase table — 65,536 UTF-16 codepoints, each mapped to its
// simple uppercase form (LE u16). Total size: 131,072 bytes (128 KiB).
//
// Source: Unicode default case mapping (single-codepoint simple uppercase),
// accessed via Swift's String.uppercased(). Clean-room: NOT copied from
// GPL `mkntfs-3g`/`ntfsprogs` source. See scripts/generate_upcase_table.swift
// for the derivation rules.
//
// Regenerate:
//   swift scripts/generate_upcase_table.swift Packages/NTFSCore/Sources/NTFSCore/UpcaseTable.swift

import Foundation

public enum UpcaseTable {
    /// The full 128 KiB NTFS $UpCase table, ready to be written to disk.
    public static let data: Data = Data(rawBytes)

    /// 131,072 raw little-endian bytes (65,536 UTF-16 codepoints).
    public static let rawBytes: [UInt8] = [

"""
for i in stride(from: 0, to: bytes.count, by: 16) {
    let end = min(i + 16, bytes.count)
    let chunk = bytes[i..<end].map { String(format: "0x%02X", $0) }.joined(separator: ", ")
    out += "        \(chunk),\n"
}
out += """
    ]
}

"""

try out.write(toFile: outPath, atomically: true, encoding: .utf8)
FileHandle.standardError.write(Data("Wrote \(bytes.count) bytes (\(bytes.count/1024) KiB) → \(outPath)\n".utf8))
